services:
  codevault:
    build: .
    image: codevault
    container_name: codevault
    ports:
      - "5174:5174"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
